apiVersion: v2
name: hologram-generic-verifier-chart
description: A Helm chart for deploying the Generic Verifier application
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: vs-agent-chart
    version: v1.3.2
    repository: oci://registry-1.docker.io/io2060
    condition: vs-agent-chart.enabled